"""Coding interview problems with company tags, practice links, and AI approach hints."""

PROBLEMS = [
    {
        "id": 1, "title": "Two Sum", "category": "arrays", "difficulty": "easy",
        "description": "Given an array of integers `nums` and an integer `target`, return indices of the two numbers that add up to `target`.\n\nYou may assume exactly one solution exists, and you may not use the same element twice.",
        "examples": [{"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]", "explanation": "nums[0] + nums[1] = 2 + 7 = 9"}],
        "constraints": ["2 ≤ nums.length ≤ 10⁴", "-10⁹ ≤ nums[i] ≤ 10⁹", "Only one valid answer exists"],
        "hints": ["Use a hash map to store seen numbers.", "For each number, check if target-num is already in the map."],
        "tags": ["hash-map", "array"],
        "companies": ["Google", "Amazon", "Meta", "Microsoft", "Apple"],
        "approach": "**Optimal: Hash Map O(n)**\n1. Create an empty hash map\n2. Iterate through array\n3. For each num, check if (target - num) exists in map\n4. If yes, return both indices\n5. Otherwise, store num → index in map",
        "time_complexity": "O(n)", "space_complexity": "O(n)",
        "links": {"leetcode": "https://leetcode.com/problems/two-sum/", "gfg": "https://www.geeksforgeeks.org/two-sum/", "hackerrank": "https://www.hackerrank.com/challenges/ctci-ice-cream-parlor"},
    },
    {
        "id": 2, "title": "Valid Palindrome", "category": "strings", "difficulty": "easy",
        "description": "A phrase is a palindrome if, after converting all uppercase letters to lowercase and removing all non-alphanumeric characters, it reads the same forward and backward.\n\nGiven a string `s`, return `true` if it is a palindrome.",
        "examples": [{"input": 's = "A man, a plan, a canal: Panama"', "output": "true"}],
        "constraints": ["1 ≤ s.length ≤ 2×10⁵"],
        "hints": ["Filter out non-alphanumeric chars first.", "Two pointer approach works well."],
        "tags": ["string", "two-pointers"],
        "companies": ["Meta", "Microsoft", "Amazon"],
        "approach": "**Two Pointer O(n)**\n1. Use left and right pointers\n2. Skip non-alphanumeric characters\n3. Compare characters (case-insensitive)\n4. Move pointers inward",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/valid-palindrome/", "gfg": "https://www.geeksforgeeks.org/check-if-a-string-is-palindrome/"},
    },
    {
        "id": 3, "title": "Best Time to Buy and Sell Stock", "category": "arrays", "difficulty": "easy",
        "description": "Given an array `prices` where `prices[i]` is the stock price on day `i`, maximize profit by choosing a day to buy and a future day to sell. Return max profit or 0.",
        "examples": [{"input": "prices = [7,1,5,3,6,4]", "output": "5", "explanation": "Buy day 2, sell day 5. Profit = 5."}],
        "constraints": ["1 ≤ prices.length ≤ 10⁵"],
        "hints": ["Track the minimum price seen so far.", "At each step, compute profit if selling today."],
        "tags": ["array", "greedy"],
        "companies": ["Amazon", "Google", "Goldman Sachs", "Morgan Stanley"],
        "approach": "**Sliding Window / Greedy O(n)**\n1. Track minimum price so far\n2. At each price, calculate profit = price - minPrice\n3. Update maxProfit if current profit is higher\n4. Update minPrice if current price is lower",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "gfg": "https://www.geeksforgeeks.org/best-time-to-buy-and-sell-stock/"},
    },
    {
        "id": 4, "title": "Maximum Subarray", "category": "arrays", "difficulty": "medium",
        "description": "Given an integer array `nums`, find the subarray with the largest sum and return its sum.",
        "examples": [{"input": "nums = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6", "explanation": "[4,-1,2,1] has sum 6."}],
        "constraints": ["1 ≤ nums.length ≤ 10⁵"],
        "hints": ["Kadane's algorithm: maintain current sum and global max.", "If current sum goes negative, reset to 0."],
        "tags": ["array", "dynamic-programming", "divide-and-conquer"],
        "companies": ["Microsoft", "Amazon", "LinkedIn", "Apple"],
        "approach": "**Kadane's Algorithm O(n)**\n1. Initialize currentSum = 0, maxSum = nums[0]\n2. For each num: currentSum = max(num, currentSum + num)\n3. maxSum = max(maxSum, currentSum)\n4. Return maxSum",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/maximum-subarray/", "gfg": "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/"},
    },
    {
        "id": 5, "title": "Climbing Stairs", "category": "dynamic_programming", "difficulty": "easy",
        "description": "You are climbing a staircase of `n` steps. Each time you can climb 1 or 2 steps. How many distinct ways can you reach the top?",
        "examples": [{"input": "n = 3", "output": "3", "explanation": "1+1+1, 1+2, 2+1"}],
        "constraints": ["1 ≤ n ≤ 45"],
        "hints": ["This is essentially Fibonacci.", "dp[i] = dp[i-1] + dp[i-2]"],
        "tags": ["dynamic-programming", "math"],
        "companies": ["Google", "Amazon", "Adobe"],
        "approach": "**DP / Fibonacci O(n)**\n1. Base: dp[1]=1, dp[2]=2\n2. For i from 3 to n: dp[i] = dp[i-1] + dp[i-2]\n3. Return dp[n]",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/climbing-stairs/", "gfg": "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/"},
    },
    {
        "id": 6, "title": "Reverse Linked List", "category": "linked_lists", "difficulty": "easy",
        "description": "Given the head of a singly linked list, reverse the list and return the reversed list.",
        "examples": [{"input": "head = [1,2,3,4,5]", "output": "[5,4,3,2,1]"}],
        "constraints": ["0 ≤ Number of nodes ≤ 5000"],
        "hints": ["Three pointer approach: prev, curr, next.", "Or use recursion."],
        "tags": ["linked-list", "recursion"],
        "companies": ["Microsoft", "Amazon", "Apple", "Bloomberg"],
        "approach": "**Iterative O(n)**\n1. Initialize prev = null, curr = head\n2. While curr: save next, point curr.next to prev\n3. Move prev = curr, curr = next\n4. Return prev",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/reverse-linked-list/", "gfg": "https://www.geeksforgeeks.org/reverse-a-linked-list/"},
    },
    {
        "id": 7, "title": "Valid Parentheses", "category": "strings", "difficulty": "easy",
        "description": "Given a string `s` containing just `(){}[]`, determine if the input string is valid. Open brackets must be closed by same type in correct order.",
        "examples": [{"input": 's = "()"', "output": "true"}, {"input": 's = "(]"', "output": "false"}],
        "constraints": ["1 ≤ s.length ≤ 10⁴"],
        "hints": ["Use a stack to track opening brackets.", "When closing bracket appears, check top of stack."],
        "tags": ["stack", "string"],
        "companies": ["Google", "Meta", "Amazon", "Bloomberg"],
        "approach": "**Stack O(n)**\n1. Push opening brackets onto stack\n2. For closing bracket, check if stack top matches\n3. If mismatch or stack empty → invalid\n4. At end, stack must be empty",
        "time_complexity": "O(n)", "space_complexity": "O(n)",
        "links": {"leetcode": "https://leetcode.com/problems/valid-parentheses/", "gfg": "https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-an-expression/"},
    },
    {
        "id": 8, "title": "Binary Search", "category": "arrays", "difficulty": "easy",
        "description": "Given a sorted array `nums` and a `target`, return the index of target if found, else -1.",
        "examples": [{"input": "nums = [-1,0,3,5,9,12], target = 9", "output": "4"}],
        "constraints": ["1 ≤ nums.length ≤ 10⁴", "All integers are unique", "Sorted ascending"],
        "hints": ["Maintain left and right pointers.", "mid = (left + right) // 2"],
        "tags": ["binary-search", "array"],
        "companies": ["Google", "Microsoft", "Apple"],
        "approach": "**Binary Search O(log n)**\n1. Set left=0, right=len-1\n2. While left<=right: mid = (left+right)//2\n3. If nums[mid]==target return mid\n4. If nums[mid]<target: left=mid+1 else right=mid-1",
        "time_complexity": "O(log n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/binary-search/", "gfg": "https://www.geeksforgeeks.org/binary-search/"},
    },
    {
        "id": 9, "title": "House Robber", "category": "dynamic_programming", "difficulty": "medium",
        "description": "Rob houses along a street without robbing two adjacent houses. Given array `nums` of money per house, return max amount.",
        "examples": [{"input": "nums = [2,7,9,3,1]", "output": "12"}],
        "constraints": ["1 ≤ nums.length ≤ 100"],
        "hints": ["dp[i] = max(dp[i-1], dp[i-2] + nums[i])", "Track two previous values."],
        "tags": ["dynamic-programming", "array"],
        "companies": ["Amazon", "Google", "Cisco"],
        "approach": "**DP O(n)**\n1. dp[0]=nums[0], dp[1]=max(nums[0],nums[1])\n2. For each i≥2: dp[i] = max(dp[i-1], dp[i-2]+nums[i])\n3. Return dp[n-1]",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/house-robber/", "gfg": "https://www.geeksforgeeks.org/find-maximum-possible-stolen-value-houses/"},
    },
    {
        "id": 10, "title": "Longest Common Prefix", "category": "strings", "difficulty": "easy",
        "description": "Find the longest common prefix string amongst an array of strings. Return empty string if none.",
        "examples": [{"input": 'strs = ["flower","flow","flight"]', "output": '"fl"'}],
        "constraints": ["1 ≤ strs.length ≤ 200"],
        "hints": ["Sort and compare first/last.", "Or zip all strings."],
        "tags": ["string"],
        "companies": ["Google", "Amazon", "Adobe"],
        "approach": "**Vertical Scan O(S)**\n1. Take first string as reference\n2. Compare each char position across all strings\n3. Stop when mismatch found\n4. Return prefix built so far",
        "time_complexity": "O(S)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/longest-common-prefix/", "gfg": "https://www.geeksforgeeks.org/longest-common-prefix-using-sorting/"},
    },
    {
        "id": 11, "title": "Merge Two Sorted Lists", "category": "linked_lists", "difficulty": "easy",
        "description": "Merge two sorted linked lists into one sorted list by splicing nodes together.",
        "examples": [{"input": "l1 = [1,2,4], l2 = [1,3,4]", "output": "[1,1,2,3,4,4]"}],
        "constraints": ["0 ≤ list length ≤ 50"],
        "hints": ["Use a dummy node.", "Compare heads and pick smaller."],
        "tags": ["linked-list", "recursion"],
        "companies": ["Microsoft", "Amazon", "Apple"],
        "approach": "**Two Pointer O(n+m)**\n1. Create dummy node\n2. Compare heads of both lists\n3. Attach smaller to result, advance that pointer\n4. Attach remaining list",
        "time_complexity": "O(n+m)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/merge-two-sorted-lists/", "gfg": "https://www.geeksforgeeks.org/merge-two-sorted-linked-lists/"},
    },
    {
        "id": 12, "title": "Container With Most Water", "category": "arrays", "difficulty": "medium",
        "description": "Given array `height`, find two lines that together with x-axis form a container holding the most water.",
        "examples": [{"input": "height = [1,8,6,2,5,4,8,3,7]", "output": "49"}],
        "constraints": ["2 ≤ height.length ≤ 10⁵"],
        "hints": ["Two pointers from both ends.", "Move the shorter line inward."],
        "tags": ["array", "two-pointers", "greedy"],
        "companies": ["Amazon", "Google", "Goldman Sachs", "Meta"],
        "approach": "**Two Pointer O(n)**\n1. Left=0, Right=end\n2. Area = min(h[l],h[r]) × (r-l)\n3. Move pointer with shorter height\n4. Track max area",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/container-with-most-water/", "gfg": "https://www.geeksforgeeks.org/container-with-most-water/"},
    },
    {
        "id": 13, "title": "3Sum", "category": "arrays", "difficulty": "medium",
        "description": "Given array nums, find all unique triplets [a,b,c] where a+b+c = 0.",
        "examples": [{"input": "nums = [-1,0,1,2,-1,-4]", "output": "[[-1,-1,2],[-1,0,1]]"}],
        "constraints": ["3 ≤ nums.length ≤ 3000"],
        "hints": ["Sort array first.", "Fix one element, use two pointers for remaining."],
        "tags": ["array", "two-pointers", "sorting"],
        "companies": ["Meta", "Amazon", "Google", "Bloomberg"],
        "approach": "**Sort + Two Pointer O(n²)**\n1. Sort the array\n2. For each i, use two pointers (i+1, end)\n3. Skip duplicates\n4. If sum<0: move left; sum>0: move right",
        "time_complexity": "O(n²)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/3sum/", "gfg": "https://www.geeksforgeeks.org/find-a-triplet-that-sum-to-a-given-value/"},
    },
    {
        "id": 14, "title": "Longest Substring Without Repeating Characters", "category": "strings", "difficulty": "medium",
        "description": "Given string `s`, find the length of the longest substring without repeating characters.",
        "examples": [{"input": 's = "abcabcbb"', "output": "3", "explanation": '"abc" length 3'}],
        "constraints": ["0 ≤ s.length ≤ 5×10⁴"],
        "hints": ["Sliding window with a set.", "Expand right, shrink left on duplicate."],
        "tags": ["hash-map", "string", "sliding-window"],
        "companies": ["Amazon", "Google", "Meta", "Bloomberg", "Microsoft"],
        "approach": "**Sliding Window O(n)**\n1. Use set to track chars in window\n2. Expand right pointer\n3. If duplicate, shrink left until no duplicate\n4. Track max window size",
        "time_complexity": "O(n)", "space_complexity": "O(min(n,26))",
        "links": {"leetcode": "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "gfg": "https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/"},
    },
    {
        "id": 15, "title": "Merge Intervals", "category": "arrays", "difficulty": "medium",
        "description": "Given array of intervals, merge all overlapping intervals and return non-overlapping intervals.",
        "examples": [{"input": "intervals = [[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]"}],
        "constraints": ["1 ≤ intervals.length ≤ 10⁴"],
        "hints": ["Sort by start time.", "Compare current end with next start."],
        "tags": ["array", "sorting"],
        "companies": ["Google", "Meta", "Microsoft", "Uber"],
        "approach": "**Sort + Merge O(n log n)**\n1. Sort intervals by start\n2. For each interval, if overlaps with last merged → extend end\n3. Otherwise, add new interval to result",
        "time_complexity": "O(n log n)", "space_complexity": "O(n)",
        "links": {"leetcode": "https://leetcode.com/problems/merge-intervals/", "gfg": "https://www.geeksforgeeks.org/merging-intervals/"},
    },
    {
        "id": 16, "title": "LRU Cache", "category": "design", "difficulty": "hard",
        "description": "Design a data structure for Least Recently Used (LRU) cache. Implement get and put with O(1) time.",
        "examples": [{"input": "LRUCache(2), put(1,1), put(2,2), get(1)", "output": "1"}],
        "constraints": ["1 ≤ capacity ≤ 3000"],
        "hints": ["HashMap + Doubly Linked List.", "Move accessed node to front."],
        "tags": ["hash-map", "linked-list", "design"],
        "companies": ["Amazon", "Google", "Meta", "Microsoft", "Netflix"],
        "approach": "**HashMap + DLL O(1)**\n1. HashMap maps key → DLL node\n2. DLL maintains access order (MRU at head)\n3. get: move node to head, return value\n4. put: add/update at head, evict tail if full",
        "time_complexity": "O(1)", "space_complexity": "O(capacity)",
        "links": {"leetcode": "https://leetcode.com/problems/lru-cache/", "gfg": "https://www.geeksforgeeks.org/lru-cache-implementation/"},
    },
    {
        "id": 17, "title": "Number of Islands", "category": "trees", "difficulty": "medium",
        "description": "Given a 2D grid of '1's (land) and '0's (water), count the number of islands.",
        "examples": [{"input": 'grid = [["1","1","0"],["1","1","0"],["0","0","1"]]', "output": "2"}],
        "constraints": ["1 ≤ m, n ≤ 300"],
        "hints": ["BFS or DFS from each unvisited land cell.", "Mark visited cells."],
        "tags": ["bfs", "dfs", "graph", "matrix"],
        "companies": ["Amazon", "Google", "Meta", "Microsoft"],
        "approach": "**DFS/BFS O(m×n)**\n1. Iterate through grid\n2. When '1' found, increment count\n3. DFS/BFS to mark all connected land as visited\n4. Continue scanning",
        "time_complexity": "O(m×n)", "space_complexity": "O(m×n)",
        "links": {"leetcode": "https://leetcode.com/problems/number-of-islands/", "gfg": "https://www.geeksforgeeks.org/find-number-of-islands/"},
    },
    {
        "id": 18, "title": "Product of Array Except Self", "category": "arrays", "difficulty": "medium",
        "description": "Given array nums, return array where answer[i] is product of all elements except nums[i]. No division allowed.",
        "examples": [{"input": "nums = [1,2,3,4]", "output": "[24,12,8,6]"}],
        "constraints": ["2 ≤ nums.length ≤ 10⁵"],
        "hints": ["Use prefix and suffix products.", "Two passes: left-to-right, right-to-left."],
        "tags": ["array", "prefix-sum"],
        "companies": ["Amazon", "Meta", "Apple", "Microsoft"],
        "approach": "**Prefix/Suffix O(n)**\n1. Left pass: prefix[i] = product of all before i\n2. Right pass: multiply by suffix product\n3. Result built in-place",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/product-of-array-except-self/", "gfg": "https://www.geeksforgeeks.org/a-product-array-puzzle/"},
    },
    {
        "id": 19, "title": "Coin Change", "category": "dynamic_programming", "difficulty": "medium",
        "description": "Given coins of different denominations and amount, return fewest coins to make that amount. Return -1 if impossible.",
        "examples": [{"input": "coins = [1,2,5], amount = 11", "output": "3", "explanation": "5+5+1 = 11"}],
        "constraints": ["1 ≤ coins.length ≤ 12", "0 ≤ amount ≤ 10⁴"],
        "hints": ["Bottom-up DP.", "dp[i] = min coins needed for amount i."],
        "tags": ["dynamic-programming", "bfs"],
        "companies": ["Amazon", "Google", "Goldman Sachs"],
        "approach": "**Bottom-Up DP O(amount × coins)**\n1. dp[0]=0, dp[1..amount]=infinity\n2. For each amount i, try each coin\n3. dp[i] = min(dp[i], dp[i-coin]+1)\n4. Return dp[amount] or -1",
        "time_complexity": "O(amount × n)", "space_complexity": "O(amount)",
        "links": {"leetcode": "https://leetcode.com/problems/coin-change/", "gfg": "https://www.geeksforgeeks.org/find-minimum-number-of-coins-that-make-a-change/"},
    },
    {
        "id": 20, "title": "Trapping Rain Water", "category": "arrays", "difficulty": "hard",
        "description": "Given elevation map, compute how much water can be trapped after raining.",
        "examples": [{"input": "height = [0,1,0,2,1,0,1,3,2,1,2,1]", "output": "6"}],
        "constraints": ["1 ≤ n ≤ 2×10⁴"],
        "hints": ["Water at i = min(maxLeft, maxRight) - height[i].", "Two pointer approach."],
        "tags": ["array", "two-pointers", "stack", "dynamic-programming"],
        "companies": ["Amazon", "Google", "Goldman Sachs", "Meta", "Uber"],
        "approach": "**Two Pointer O(n)**\n1. Left and right pointers, track maxLeft, maxRight\n2. Process shorter side first\n3. Water += max - height at that pointer\n4. Move pointer inward",
        "time_complexity": "O(n)", "space_complexity": "O(1)",
        "links": {"leetcode": "https://leetcode.com/problems/trapping-rain-water/", "gfg": "https://www.geeksforgeeks.org/trapping-rain-water/"},
    },
]

# DSA Roadmap for the preparation section
DSA_ROADMAP = [
    {"week": 1, "title": "Arrays & Hashing", "topics": ["Two Pointers", "Hash Maps", "Prefix Sum"], "problems": [1, 3, 8, 18]},
    {"week": 2, "title": "Strings & Sliding Window", "topics": ["String Manipulation", "Sliding Window", "Two Pointers"], "problems": [2, 7, 10, 14]},
    {"week": 3, "title": "Linked Lists", "topics": ["Reversal", "Merge", "Fast/Slow Pointer"], "problems": [6, 11]},
    {"week": 4, "title": "Stacks & Queues", "topics": ["Stack Operations", "Monotonic Stack", "Queue"], "problems": [7, 20]},
    {"week": 5, "title": "Trees & Graphs", "topics": ["BFS", "DFS", "Binary Trees"], "problems": [17]},
    {"week": 6, "title": "Dynamic Programming", "topics": ["1D DP", "2D DP", "Knapsack"], "problems": [5, 9, 19]},
    {"week": 7, "title": "Advanced Patterns", "topics": ["Greedy", "Intervals", "Design"], "problems": [12, 13, 15, 16]},
    {"week": 8, "title": "Hard Problems & Review", "topics": ["Two Pointers Advanced", "DP Advanced", "System Design"], "problems": [20, 16]},
]

# Company-specific preparation paths
COMPANY_PATHS = {
    "Google": {"focus": ["Arrays", "Trees", "DP", "Graph"], "problems": [1, 4, 5, 7, 8, 15, 17, 20], "tips": "Google loves algorithmic thinking. Focus on optimal time complexity and clean code."},
    "Amazon": {"focus": ["Arrays", "Trees", "Design", "DP"], "problems": [1, 3, 6, 9, 12, 17, 18, 19], "tips": "Amazon asks Leadership Principles behavioral questions alongside coding. Practice both."},
    "Meta": {"focus": ["Arrays", "Strings", "Graphs", "DP"], "problems": [1, 2, 7, 13, 14, 15, 17], "tips": "Meta values speed. Practice solving medium problems in under 20 minutes."},
    "Microsoft": {"focus": ["Arrays", "Linked Lists", "Trees", "Design"], "problems": [1, 4, 6, 11, 15, 16, 17, 18], "tips": "Microsoft focuses on clean object-oriented design and edge case handling."},
    "Apple": {"focus": ["Arrays", "Strings", "Linked Lists"], "problems": [1, 6, 11, 18], "tips": "Apple values elegant, readable solutions. Focus on code quality over brute force."},
}


def get_problem(problem_id: int) -> dict | None:
    return next((p for p in PROBLEMS if p["id"] == problem_id), None)


def get_problems(category: str = None, difficulty: str = None) -> list[dict]:
    result = PROBLEMS
    if category and category != "all":
        result = [p for p in result if p["category"] == category]
    if difficulty and difficulty != "all":
        result = [p for p in result if p["difficulty"] == difficulty]
    return [
        {"id": p["id"], "title": p["title"], "category": p["category"],
         "difficulty": p["difficulty"], "tags": p["tags"], "companies": p.get("companies", []),
         "links": p.get("links", {})}
        for p in result
    ]
